# Setup
title:               martinezhero.org
tagline:             things
url:                 http://martinezhero.org
baseurl:             ""

# Assets
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Josef Kelly
  url:               https://twitter.com/josefkelly
  email:             kelly.josef@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/martinez-hero/martinez-hero.github.io